apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: stablecoin
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: t838pD"bV)0Q
  POSTGRES_DB: postgres
  DATABASE_URL: postgres://postgres:t838pD"bV)0Q@postgres-external:5432/postgres
